name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from GitHub
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Docker on the GitHub Runner
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Log in to Docker Hub (you will store credentials in GitHub Secrets)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the Docker image (You can change the context and Dockerfile path)
    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/react-web-app .

    # Push the Docker image to Docker Hub
    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/react-web-app
